---
version: 2

updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily

  - package-ecosystem: opentofu # https://github.com/opentofu/opentofu/issues/1236
    directories:
      - /sample/bucket
      - /sample/instance
    schedule:
      interval: weekly
    groups:
      terraform:
        patterns:
          - "*"
