version: 2

updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily

  # Wildcard support: https://github.com/dependabot/dependabot-core/issues/2178

  - package-ecosystem: terraform
    directory: stacks/sample_bucket
    schedule:
      interval: daily

  - package-ecosystem: terraform
    directory: stacks/sample_instance
    schedule:
      interval: daily

  - package-ecosystem: terraform
    directory: environments/bravo
    schedule:
      interval: daily

  - package-ecosystem: terraform
    directory: environments/connect
    schedule:
      interval: daily

  - package-ecosystem: terraform
    directory: environments/demo
    schedule:
      interval: daily
