---
name: Trigger on schedule (cron) event with 'fmt' and 'validate' checks to identify configuration drift.

on:
  schedule:
    - cron: "0 */8 * * 1-5" # Every 8 hours on weekdays.

jobs:
  tf:
    runs-on: ubuntu-latest

    permissions:
      actions: read        # Required to identify workflow run.
      checks: write        # Required to add status summary.
      contents: read       # Required to checkout repository.
      pull-requests: write # Required to add comment and label.

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup TF
        uses: hashicorp/setup-terraform@v3

      - name: Provision TF
        id: provision
        uses: devsectop/tf-via-pr@v12
        with:
          command: plan
          arg-lock: false
          arg-parallelism: 20
          arg-refresh-only: true
          working-directory: path/to/directory
          plan-encrypt: ${{ secrets.PASSPHRASE }}
          format: true
          validate: true

      - name: Check drift
        if: steps.provision.outputs.exitcode != 0
        run: echo "Configuration drift detected."
