---
name: TF via PR Input with AWS Authentication
on:
  pull_request:
    types: [opened, reopened, synchronize, closed]
    paths: ['**/*.tf*']

jobs:
  tf:
    runs-on: ubuntu-latest
    if: github.event.action != 'closed' || github.event.pull_request.merged

    permissions:
      actions: read # Required for workflow query and artifact download.
      checks: write # Required for adding summary to check status.
      contents: read # Required for repository checkout.
      id-token: write # Required for assuming AWS role via OIDC provider.
      pull-requests: write # Required for commenting on PR.

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: us-east-1
          role-to-assume: ${{ secrets.AWS_ROLE }}

      - name: Setup TF
        uses: hashicorp/setup-terraform@v3

      - name: Provision TF
        uses: devsectop/tf-via-pr-comments@v10
        env:
          TF_VAR_PLACEHOLDER: value
        with:
          backend_config_prefix: backend/
          backend_config_suffix: .tfvars
          chdir_prefix: sample/
          command_input: ${{ format('-tf={0} -chdir=sample_bucket -backend-config=dev', github.event.action != 'closed' && 'plan' || 'apply') }}
