name: TF via PR Input Matrix Strategy

on:
  pull_request:
    types: [opened, reopened, synchronize, closed]
    paths: ["**/*.tf*"]

jobs:
  tf:
    runs-on: ubuntu-latest
    if: github.event.action != 'closed' || github.event.pull_request.merged

    permissions:
      actions: read # Required for workflow query and artifact download.
      contents: read # Required for repository checkout.
      pull-requests: write # Required for commenting on PR.

    strategy:
      fail-fast: false
      matrix:
        deployment: [dev, stg, prd]

    steps:
      - name: Checkout repository
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - name: Setup TF
        uses: opentofu/setup-opentofu@ae80d4ecaab946d8f5ff18397fbf6d0686c6d46a # v1.0.3

      - name: Provision TF
        id: tf
        uses: devsectop/tf-via-pr-comments@069fd20e039d1ee5fba48b8a319752e44451782a # v10
        env:
          TF_VAR_PLACEHOLDER: value
        with:
          command_input: ${{ format('-tf={0} -chdir=sample/sample_bucket -backend-config=backend/{1}.tfvars', github.event.action != 'closed' && 'plan' || 'apply', matrix.deployment) }}

      - name: Echo TF
        run: |
          echo "command: ${{ steps.tf.outputs.command }}"
          echo "plan_id: ${{ steps.tf.outputs.plan_id }}"
          echo "tf_fmt: ${{ steps.tf.outputs.tf_fmt }}"
          echo "tf_output: ${{ steps.tf.outputs.tf_output }}"
