---
name: TF via PR Comments
on:
  issue_comment:
    types: [created, edited]
  pull_request:
    types: [synchronize]
    paths: ['**/*.tf*']

jobs:
  tf:
    runs-on: ubuntu-latest
    if: startsWith(github.event.comment.body, '-tf=') || contains(join(github.event.pull_request.labels.*.name), 'tf:')

    permissions:
      actions: read # Required for workflow query and artifact download.
      checks: write # Required for adding summary to check status.
      contents: read # Required for repository checkout.
      issues: read # Required for getting PR branch from issue comment.
      pull-requests: write # Required for commenting on PR.
      statuses: write # Required for setting commit status from issue comment.

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.issue && format('refs/pull/{0}/merge', github.event.issue.number) }}

      - name: Setup TF
        uses: hashicorp/setup-terraform@v3

      - name: Provision TF
        uses: devsectop/tf-via-pr@v10
        env:
          TF_VAR_PLACEHOLDER: value
        with:
          recreate_comment: true
          var_file_from_workspace: true
          var_file_prefix: env/
          var_file_suffix: .tfvars
          chdir_prefix: sample/
