name: TF via PR Comments or Input

on:
  issue_comment:
    types: [created, edited]
  pull_request:
    types: [opened, reopened, synchronize, closed]
    paths: ["**/*.tf*"]

jobs:
  tf:
    runs-on: ubuntu-latest
    if: startsWith(github.event.comment.body, '-tf=') || github.event.action != 'closed' || github.event.pull_request.merged

    permissions:
      actions: read # Required for workflow query and artifact download.
      contents: read # Required for repository checkout.
      issues: read # Required for getting PR branch from issue comment.
      pull-requests: write # Required for commenting on PR.
      statuses: write # Required for setting commit status from issue comment.

    steps:
      - name: Checkout repository
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        with:
          ref: ${{ github.event.issue && format('refs/pull/{0}/merge', github.event.issue.number) }}

      - name: Setup TF
        uses: opentofu/setup-opentofu@ae80d4ecaab946d8f5ff18397fbf6d0686c6d46a # v1.0.3

      - name: Provision TF
        uses: devsectop/tf-via-pr-comments@069fd20e039d1ee5fba48b8a319752e44451782a # v10
        env:
          TF_VAR_PLACEHOLDER: value
        with:
          recreate_comment: true
          var_file_from_workspace: true
          command_input: ${{ github.event.comment && '' || format('-tf={0} -chdir=sample/sample_instance -workspace=dev', github.event.action != 'closed' && 'plan' || 'apply') }}
          var_file_prefix: env/
          var_file_suffix: .tfvars
