name: Terraform

on: # https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows.
  issue_comment:
    types: [created, edited]

# permissions:
#   id-token: write # (Optional) Required by aws-actions/configure-aws-credentials for OIDC authentication.

jobs:
  terraform: # Parse terraform command(s) from comment body and run on PR branch.

    # uses: devsectop/tf-via-pr/.github/workflows/tf.yml@main
    uses: ./.github/workflows/tf.yml

    secrets:
      env_vars: |
        CONFIGURE_AWS_CREDENTIALS=true
        CONFIGURE_AWS_REGION=us-east-1
        CONFIGURE_AWS_ROLE_TO_ASSUME=${{ secrets.AWS_ROLE_TO_ASSUME }}
        TF_VAR_PREFIX=${{ secrets.TF_VAR_PREFIX }}
