name: TF Caller

on:
  issue_comment:
    types: [created, edited]
  pull_request:
    types: [synchronize]
    paths: ['**/*.tf*']

jobs:
  tf:
    uses: ./.github/workflows/tf.yml
  # uses: devsectop/tf-via-pr/.github/workflows/tf.yml@main
    secrets:
      env_vars: |
        AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}
        TVP_CHDIR_PREFIX=stacks/
        TVP_CLI_USES=tofu
        TVP_CLI_VERSION=~1.6
        TF_VAR_PREFIX=${{ secrets.TF_VAR_PREFIX }}
      # TF_LOG=debug
