name: Terraform

on: # https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows.
  issue_comment:
    types: [created, edited]

  pull_request:
    types: [synchronize]

permissions:
  contents: read # Required by actions/checkout.
  deployments: write # Required by bobheadxi/deployments.
  id-token: write # Required by aws-actions/configure-aws-credentials.
  issues: read # Required by xt0rted/pull-request-comment-branch.
  pull-requests: write # Required by dflook/terraform-*.
  statuses: write # Required by myrotvorets/set-commit-status-action.

jobs:
  terraform:
    uses: ./.github/workflows/tf.yml
    # uses: devsectop/tf-via-pr/.github/workflows/tf.yml@main

    secrets:
      env_vars: |
        CONFIGURE_AWS_CREDENTIALS=true
        CONFIGURE_AWS_REGION=us-east-1
        CONFIGURE_AWS_ROLE=${{ secrets.AWS_ROLE }}
        TF_VAR_PREFIX=${{ secrets.TF_VAR_PREFIX }}
