name: Terraform

on:
  issue_comment:
    types: [created, edited]
  pull_request:
    types: [synchronize]

jobs:
  terraform:
    uses: ./.github/workflows/tf.yml
  # uses: devsectop/tf-via-pr/.github/workflows/tf.yml@main
    secrets:
      env_vars: |
        AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}
        CONFIG_TF_CHDIR_PREFIX=stacks/
        TF_VAR_PREFIX=${{ secrets.TF_VAR_PREFIX }}
