name: TF Caller with AWS

on:
  issue_comment:
    types: [created, edited]
  pull_request:
    types: [synchronize]
    paths: ['**/*.tf*']

jobs:
  credentials:
    if: startsWith(github.event.comment.body, '-tf=') || contains(join(github.event.pull_request.labels.*.name), 'tf:')
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    outputs:
      AWS_ACCESS_KEY_ID: ${{ steps.credentials.outputs.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ steps.credentials.outputs.AWS_SECRET_ACCESS_KEY }}
      AWS_SESSION_TOKEN: ${{ steps.credentials.outputs.AWS_SESSION_TOKEN }}
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@010d0da01d0b5a38af31e9c3470dbfdabdecca3a # v4.0.1
        with:
          aws-region: us-east-1
          role-to-assume: ${{ secrets.AWS_ROLE }}
      - name: Output credentials
        id: credentials
        run: |
          echo "AWS_ACCESS_KEY_ID=$(echo $AWS_ACCESS_KEY_ID | base64 -w0 | base64 -w0)" >> $GITHUB_OUTPUT
          echo "AWS_SECRET_ACCESS_KEY=$(echo $AWS_SECRET_ACCESS_KEY | base64 -w0 | base64 -w0)" >> $GITHUB_OUTPUT
          echo "AWS_SESSION_TOKEN=$(echo $AWS_SESSION_TOKEN | base64 -w0 | base64 -w0)" >> $GITHUB_OUTPUT

  tf:
    needs: credentials
    uses: ./.github/workflows/tf.yml
  # uses: devsectop/tf-via-pr/.github/workflows/tf.yml@main
    secrets:
      env_vars: |
        BASE64_AWS_ACCESS_KEY_ID=${{ needs.credentials.outputs.AWS_ACCESS_KEY_ID }}
        BASE64_AWS_SECRET_ACCESS_KEY=${{ needs.credentials.outputs.AWS_SECRET_ACCESS_KEY }}
        BASE64_AWS_SESSION_TOKEN=${{ needs.credentials.outputs.AWS_SESSION_TOKEN }}
        TVP_CHDIR_PREFIX=stacks/
        TVP_CLI_USES=tofu
        TVP_CLI_VERSION=1.6.0-alpha3
        TF_VAR_PREFIX=${{ secrets.TF_VAR_PREFIX }}
      # TF_LOG=debug

  results:
    needs: tf
    runs-on: ubuntu-latest
    steps:
      - name: Display TF results
        run: |
          echo "COMMENT_SHA=${{ needs.tf.outputs.COMMENT_SHA }}"
          echo "PARSED_COMMENT=${{ needs.tf.outputs.PARSED_COMMENT }}"
          echo "PROMPT_MATRIX=${{ needs.tf.outputs.PROMPT_MATRIX }}"
          echo "TF_PLAN_ID=${{ needs.tf.outputs.TF_PLAN_ID }}"
          echo "WORKING_DIRECTORY=${{ needs.tf.outputs.WORKING_DIRECTORY }}"
