---
name: CI Release Tag

on:
  release:
    types: [created]

jobs:
  tag:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938 # v4.2.0

      - name: Fetch major version tag and update it
        shell: bash
        run: |
          VERSION=${GITHUB_REF#refs/tags/}
          MAJOR=${VERSION%%.*}
          git config --global user.name 'Rishav Dhar'
          git config --global user.email '19497993+rdhar@users.noreply.github.com'
          git tag -fa "${MAJOR}" -m 'Update major version tag'
          git push origin "${MAJOR}" --force
