name: Terraform

on:
  # For terraform plan
  pull_request:
    types: [synchronize, reopened, labeled, unlabeled]

  # For terraform apply
  push:
    branches: [main]

  # Fallback for manual trigger
  workflow_dispatch:
    inputs:
      terraform:
        required: true
        type: choice
        default: plan
        options: [plan, apply]

# Run a single terraform workflow per branch along with a fallback for concurrent runs
concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}

# Use bash for string manipulation
defaults:
  run:
    shell: bash

# For GITHUB_TOKEN to amend pull request comments
permissions:
  contents: read
  pull-requests: write

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_REGION: ${{ secrets.AWS_REGION }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  # Get the list of labels on the PR or commit
  environments:
    runs-on: ubuntu-latest

    # Store the list of labels for subsequent jobs
    outputs:
      matrix: ${{ steps.set_matrix.outputs.result }}

    steps:
      # Query GitHub API via @octokit/core
      - name: Set matrix
        uses: actions/github-script@v6
        id: set_matrix
        with:
          script: |
            return (
              await github.rest.repos.listPullRequestsAssociatedWithCommit({
                commit_sha: context.payload.after,
                owner: context.repo.owner,
                repo: context.repo.repo,
              })
            ).data[0].labels
              .filter((label) => label.name.startsWith('tf'))
              .map((label) => {
                let [prefix, suffix] = label.name.split(':');
                return [prefix, suffix];
              });

  plan:
    # Terraform plan only on pull_request event if one or more environments are present
    if: (github.event_name == 'pull_request' || inputs.terraform == 'plan') && needs.environments.outputs.matrix != '' && toJson(fromJson(needs.environments.outputs.matrix)) != '[]'
    runs-on: ubuntu-latest
    needs: [environments]

    # Run for each label and continue through to release state lock
    strategy:
      fail-fast: false
      matrix:
        path: ${{ fromJSON(needs.environments.outputs.matrix) }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set local variables
      - name: Local variables
        run: |
          string="${{ matrix.path }}"
          echo tf_label=${string/*:/} >> $GITHUB_ENV
          if [[ $string == *"--"* ]]; then
            prefix=${string/--*/}
            echo tf_action=${prefix/:*/} >> $GITHUB_ENV
            echo tf_environment=${prefix/*:/} >> $GITHUB_ENV
            echo tf_workspace=${string/*--/} >> $GITHUB_ENV
          else
            echo tf_action=${string/:*/} >> $GITHUB_ENV
            echo tf_environment=${string/*:/} >> $GITHUB_ENV
            echo tf_workspace="default" >> $GITHUB_ENV
          fi

      - name: debug
        run: |
          echo ${{ env.tf_label }}
          echo ${{ env.tf_action }}
          echo ${{ env.tf_environment }}
          echo ${{ env.tf_workspace }}

      # Initialise terraform workspace if required
      - name: Terraform workspace
        if: env.tf_workspace != 'default'
        uses: dflook/terraform-new-workspace@v1
        with:
          workspace: ${{ env.tf_workspace }}
          path: environments/${{ env.tf_environment }}
          backend_config_file: environments/backend.tfvars
          backend_config: key=environments/${{ env.tf_environment }}/terraform.tfstate

      # Run terraform plan with environment and workspace
      - name: Terraform plan
        uses: dflook/terraform-plan@v1
        with:
          label: ${{ env.tf_label }}
          workspace: ${{ env.tf_workspace }}
          path: environments/${{ env.tf_environment }}
          backend_config_file: environments/backend.tfvars
          backend_config: key=environments/${{ env.tf_environment }}/terraform.tfstate

      # Run terraform apply with environment and workspace if 'tf_preview' prefix is present
      - name: Terraform apply
        if: env.tf_action == 'tf_preview'
        uses: dflook/terraform-apply@v1
        with:
          label: ${{ env.tf_label }}
          workspace: ${{ env.tf_workspace }}
          path: environments/${{ env.tf_environment }}
          backend_config_file: environments/backend.tfvars
          backend_config: key=environments/${{ env.tf_environment }}/terraform.tfstate

    # Set GitHub environment to track deployment status
    # environment:
    #   name: ${{ env.tf_label }}
    #   url: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}

  apply:
    # Terraform apply only on push event if one or more environments are present
    if: (github.event_name == 'push' || inputs.terraform == 'apply') && needs.environments.outputs.matrix != '' && toJson(fromJson(needs.environments.outputs.matrix)) != '[]'
    runs-on: ubuntu-latest
    needs: [environments]

    # Run for each label and continue through to release state lock
    strategy:
      fail-fast: false
      matrix:
        path: ${{ fromJSON(needs.environments.outputs.matrix) }}

    # Set GitHub environment to track deployment status
    # environment:
    #   name: ${env.tf_label/*:/}
    #   url: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
    # name: ${{ env.tf_label }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set local variables
      - name: Local variables
        run: |
          string="${{ matrix.path }}"
          echo tf_label=${string/*:/} >> $GITHUB_ENV
          if [[ $string == *"--"* ]]; then
            prefix=${string/--*/}
            echo tf_action=${prefix/:*/} >> $GITHUB_ENV
            echo tf_environment=${prefix/*:/} >> $GITHUB_ENV
            echo tf_workspace=${string/*--/} >> $GITHUB_ENV
          else
            echo tf_action=${string/:*/} >> $GITHUB_ENV
            echo tf_environment=${string/*:/} >> $GITHUB_ENV
            echo tf_workspace="default" >> $GITHUB_ENV
          fi

      # Run terraform apply with environment and workspace
      - name: Terraform apply
        uses: dflook/terraform-apply@v1
        with:
          label: ${{ env.tf_label }}
          workspace: ${{ env.tf_workspace }}
          path: environments/${{ env.tf_environment }}
          backend_config_file: environments/backend.tfvars
          backend_config: key=environments/${{ env.tf_environment }}/terraform.tfstate
