name: Terraform (Multiple AWS) Via PR Comments — Reusable Workflow

# This reusable workflow parses PR comments for terraform commands and then
# run them on the branch in parallel with AWS authentication. Learn more:
# https://github.com/devsectop/tf-via-pr/#readme

on:
  workflow_call:
    secrets:
      env_vars:
        description: Environment variables passed into this workflow.
        required: false

permissions:
  actions: read # Required for (up/down)loading artifacts
  contents: read # Required for actions/checkout
  id-token: write # Required for aws-actions/configure-aws-credentials
  issues: read # Required for forxt0rted/pull-request-comment-branch
  pull-requests: write # Required for comments and labels
  statuses: write # Required for myrotvorets/set-commit-status-action

jobs:
  # Parse the comment for terraform commands.
  pre:
    if: startsWith(github.event.comment.body, '-terraform=') || contains(join(github.event.pull_request.labels.*.name), 'terraform:')
    runs-on: ubuntu-latest

    outputs:
      commands: ${{ steps.parse_comment.outputs.result }}
      comment: ${{ steps.get_branch.outputs.head_sha }}

    steps:
      - name: Find comment
        id: find_comment
        if: github.event_name == 'pull_request'
        uses: peter-evans/find-comment@a54c31d7fa095754bfef525c0c8e5e5674c4b4b1 # v2.4.0
        with:
          body-regex: ^-terraform=plan.*
          direction: last
          issue-number: ${{ github.event.number }}

      - name: Parse comment
        id: parse_comment
        if: github.event.issue.pull_request || steps.find_comment.outputs.comment-body
        uses: actions/github-script@d7906e4ad0b1822421a7e6a35d5ca353c962f410 # v6.4.1
        env:
          comment: ${{ github.event.comment.body || steps.find_comment.outputs.comment-body }}
        with:
          script: |
            // Trim whitespace, split the comment on newlines and remove empty lines.
            return process.env.comment
              // Split the string on newlines, removing empty lines and whitespace.
              .trim()
              .split("\n")
              .filter((line) => line.trim())
              .map((line) => {
                // Split the line on spaces outside of quotation marks.
                const args = line.match(/("[^"]+"|'[^']+'|[^'"\s]+)+/g);
                const obj = {};
                args.forEach((arg) => {
                  // Split the arg on the first equals sign to assign key value pairs to the object.
                  const [key, value] = arg.split("=");
                  // Remove the leading dash from the key and remove quotation marks outside of square brackets from the value if it exists, otherwise set the value to true.
                  obj[key.slice(1)] = value?.replace(/['"]+(?![^\[]*\])/g, "") || true;
                });
                return obj;
              });

      - name: Get comment branch
        id: get_branch
        if: github.event.issue.pull_request
        uses: xt0rted/pull-request-comment-branch@d97294d304604fa98a2600a6e2f916a84b596dc7 # v2.0.0

      - name: Add commit status
        if: github.event.issue.pull_request
        uses: myrotvorets/set-commit-status-action@243b4f7e597f62335408d58001edf8a02cf3e1fd # v1.1.7
        with:
          sha: ${{ steps.get_branch.outputs.head_sha }}

  # Run terraform commands on the branch associated with the comment.
  run:
    needs: [pre]
    runs-on: ubuntu-latest

    # Run each terraform command to completion in parallel.
    strategy:
      fail-fast: false
      matrix:
        in: ${{ fromJSON(needs.pre.outputs.commands) }}

    env:
      TF_CLI_ARGS: -no-color
      TF_IN_AUTOMATION: true
      TF_INPUT: false

    steps:
      - name: Checkout repository
        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
        with:
          ref: ${{ github.head_ref || format('refs/pull/{0}/merge', github.event.issue.number) }}

      - name: Populate environment variables
        env:
          env_vars: ${{ secrets.env_vars }}
          matrix: ${{ toJSON(matrix.in) }}
        run: |
          for i in $env_vars; do echo ::add-mask::${i/*=/}; printf '%s\n' $i >> $GITHUB_ENV; done
          echo INPUT_PROMPT=$matrix >> $GITHUB_ENV

      - name: Authenticate AWS credentials
        if: env.CONFIGURE_AWS_REGION
        uses: aws-actions/configure-aws-credentials@5fd3084fc36e372ff1fff382a39b10d03659f355 # v2.2.0
        with:
          aws-region: ${{ env.CONFIGURE_AWS_REGION }}
          role-session-name: ${{ env.CONFIGURE_AWS_SESSION_NAME }}
          role-to-assume: ${{ env.CONFIGURE_AWS_ROLE }}

      - name: Add PR label
        if: (!contains(join(github.event.pull_request.labels.*.name), format('terraform:{0}', matrix.in['terraform'])))
        uses: actions/github-script@d7906e4ad0b1822421a7e6a35d5ca353c962f410 # v6.4.1
        with:
          script: |
            const label_add = await github.rest.issues.addLabels({
              issue_number: context.issue.number,
              labels: ["terraform:${{ matrix.in['terraform'] }}"],
              owner: context.repo.owner,
              repo: context.repo.repo,
            });
            const label_color = await github.rest.issues.updateLabel({
              color: "5C4EE5",
              description: "Pull requests that ${{ matrix.in['terraform'] }} Terraform code",
              name: "terraform:${{ matrix.in['terraform'] }}",
              owner: context.repo.owner,
              repo: context.repo.repo,
            });

      - name: Setup terraform
        uses: hashicorp/setup-terraform@633666f66e0061ca3b725c73b2ec20cd13a8fdd1 # v2.0.3
        with:
          cli_config_credentials_hostname: ${{ env.CONFIGURE_TF_HOSTNAME }}
          cli_config_credentials_token: ${{ env.CONFIGURE_TF_TOKEN }}
          terraform_version: ${{ env.CONFIGURE_TF_VERSION }}

      - name: Populate terraform variables
        env:
          TF_COM_AUTO_APPROVE: ${{ matrix.in['auto-approve'] }}
          TF_COM_BACKEND_CONFIG: ${{ matrix.in['backend-config'] }}
          TF_COM_BACKEND: ${{ matrix.in['backend'] }}
          TF_COM_CHDIR: ${{ matrix.in['chdir'] != '' && format('{0}{1}', env.CONFIGURE_TF_CHDIR_PREFIX, matrix.in['chdir']) || env.CONFIGURE_TF_CHDIR_PREFIX != '' && format('{0}', env.CONFIGURE_TF_CHDIR_PREFIX) || '' }}
          TF_COM_CLOUD: ${{ matrix.in['cloud'] }}
          TF_COM_COMPACT_WARNINGS: ${{ matrix.in['compact-warnings'] }}
          TF_COM_DESTROY: ${{ matrix.in['destroy'] }}
          TF_COM_FROM_MODULE: ${{ matrix.in['from-module'] }}
          TF_COM_GET: ${{ matrix.in['get'] }}
          TF_COM_IGNORE_REMOTE_VERSION: ${{ matrix.in['ignore-remote-version'] }}
          TF_COM_LOCK_TIMEOUT: ${{ matrix.in['lock-timeout'] }}
          TF_COM_LOCK: ${{ matrix.in['lock'] }}
          TF_COM_LOCKFILE: ${{ matrix.in['lockfile'] }}
          TF_COM_PARALLELISM: ${{ matrix.in['parallelism'] }}
          TF_COM_PLUGIN_DIR: ${{ matrix.in['plugin-dir'] }}
          TF_COM_REFRESH_ONLY: ${{ matrix.in['refresh-only'] }}
          TF_COM_REFRESH: ${{ matrix.in['refresh'] }}
          TF_COM_REPLACE: ${{ matrix.in['replace'] }}
          TF_COM_TARGET: ${{ matrix.in['target'] }}
          TF_COM_TERRAFORM: ${{ matrix.in['terraform'] }}
          TF_COM_UPGRADE: ${{ matrix.in['upgrade'] }}
          TF_COM_VAR_FILE: ${{ matrix.in['var-file'] }}
        run: |
          env | grep TF_COM_ | while read -r line; do
            # Store the variable name.
            name=$(echo "$line" | cut -d= -f1)
            # Store the variable key, convert to lowercase and replace underscores with dashes.
            key=$(echo "$name" | sed 's/^TF_COM_//' | sed 's/_/-/g' | tr '[:upper:]' '[:lower:]')
            # Store the variable value and replace spaces with escaped spaces.
            value=$(echo "$line" | cut -d= -f2- | sed 's/ /\\ /g')
            # If the variable value is "true", then treat its key as a flag.
            if [ "$value" = "true" ]; then
              echo "$name=-$key" >> $GITHUB_ENV
            # Else if the variable value is non-empty, then pass it as an argument.
            elif [ -n "$value" ]; then
              # If the variable value contains a comma, then pass it as multiple arguments.
              if [ "$value" = "${value/,/}" ]; then
                echo "$name=-$key=$value" >> $GITHUB_ENV
              else
                echo "$name=-$key=${value//,/ -${key}=}" >> $GITHUB_ENV
              fi
            fi
          done
          echo "INPUT_PATH=$TF_COM_CHDIR" >> $GITHUB_ENV
          echo "INPUT_TFPLAN=$(echo ${{ format('{0} {1} {2} {3} {4} {5} tfplan', github.event.number || github.event.issue.number, matrix.in['backend-config'], matrix.in['chdir'], matrix.in['destroy'], matrix.in['var-file'], matrix.in['workspace']) }} | sed 's/[[:space:][:punct:]]/-/g')" >> $GITHUB_ENV
          if [ "$TF_COM_AUTO_APPROVE" = "" ] && [ "$TF_COM_TERRAFORM" = "apply" ]; then echo "TF_COM_VAR_FILE=" >> $GITHUB_ENV; fi
          if [ "$TF_COM_AUTO_APPROVE" = "" ]; then echo "TF_COM_AUTO_APPROVE=tfplan" >> $GITHUB_ENV; fi

      - name: Terraform init
        id: terraform_init
        run: terraform ${{ env.TF_COM_CHDIR }} init ${{ env.TF_COM_BACKEND }} ${{ env.TF_COM_BACKEND_CONFIG }} ${{ env.TF_COM_CLOUD }} ${{ env.TF_COM_FROM_MODULE }} ${{ env.TF_COM_GET }} ${{ env.TF_COM_IGNORE_REMOTE_VERSION }} ${{ env.TF_COM_LOCK }} ${{ env.TF_COM_LOCK_TIMEOUT }} ${{ env.TF_COM_LOCKFILE }} ${{ env.TF_COM_PLUGIN_DIR }} ${{ env.TF_COM_UPGRADE }}

      - name: Terraform workspace
        id: terraform_workspace
        if: matrix.in['workspace'] != ''
        run: terraform ${{ env.TF_COM_CHDIR }} workspace select "${{ matrix.in['workspace'] }}" || terraform ${{ env.TF_COM_CHDIR }} workspace new "${{ matrix.in['workspace'] }}"

      - name: Terraform plan
        id: terraform_plan
        if: matrix.in['terraform'] == 'plan'
        run: terraform ${{ env.TF_COM_CHDIR }} plan -out=tfplan ${{ env.TF_COM_COMPACT_WARNINGS }} ${{ env.TF_COM_DESTROY }} ${{ env.TF_COM_LOCK }} ${{ env.TF_COM_LOCK_TIMEOUT }} ${{ env.TF_COM_PARALLELISM }} ${{ env.TF_COM_REFRESH }} ${{ env.TF_COM_REFRESH_ONLY }} ${{ env.TF_COM_REPLACE }} ${{ env.TF_COM_TARGET }} ${{ env.TF_COM_VAR_FILE }}

      - name: Upload terraform plan
        if: matrix.in['terraform'] == 'plan' && steps.terraform_plan.outputs.exitcode == 0
        uses: actions/upload-artifact@0b7f8abb1508181956e8e162db84b466c27e18ce # v3.1.2
        with:
          name: ${{ env.INPUT_TFPLAN }}
          path: ${{ env.INPUT_PATH }}/tfplan

      - name: Download terraform plan
        id: artifact_url
        if: matrix.in['terraform'] == 'apply' && matrix.in['auto-approve'] == ''
        uses: actions/github-script@d7906e4ad0b1822421a7e6a35d5ca353c962f410 # v6.4.1
        with:
          script: |
            const { data: artifact_id } = await github.rest.actions.listArtifactsForRepo({
              name: "${{ env.INPUT_TFPLAN }}",
              owner: context.repo.owner,
              per_page: 100,
              repo: context.repo.repo,
            });
            const artifact_download = await github.rest.actions.downloadArtifact({
              archive_format: "zip",
              artifact_id: artifact_id.artifacts[0].id,
              owner: context.repo.owner,
              repo: context.repo.repo,
            });
            return artifact_download.url;

      - name: Unzip terraform plan
        if: matrix.in['terraform'] == 'apply' && matrix.in['auto-approve'] == ''
        run: wget -O ${{ env.INPUT_TFPLAN }} ${{ steps.artifact_url.outputs.result }} && unzip ${{ env.INPUT_TFPLAN }} -d "${{ env.INPUT_PATH }}"

      - name: Terraform apply
        id: terraform_apply
        if: matrix.in['terraform'] == 'apply'
        run: terraform ${{ env.TF_COM_CHDIR }} apply ${{ env.TF_COM_COMPACT_WARNINGS }} ${{ env.TF_COM_DESTROY }} ${{ env.TF_COM_LOCK }} ${{ env.TF_COM_LOCK_TIMEOUT }} ${{ env.TF_COM_PARALLELISM }} ${{ env.TF_COM_REFRESH }} ${{ env.TF_COM_REFRESH_ONLY }} ${{ env.TF_COM_REPLACE }} ${{ env.TF_COM_TARGET }} ${{ env.TF_COM_VAR_FILE }} ${{ env.TF_COM_AUTO_APPROVE }}

      - name: Terraform force-unlock
        id: terraform_force_unlock
        if: matrix.in['terraform'] == 'force-unlock'
        run: terraform ${{ env.TF_COM_CHDIR }} force-unlock -force "${{ matrix.in['lock-id'] }}"

      # If any terraform commands are run, then add a PR comment with the latest output.
      - name: Comment terraform output
        if: ${{ (success() || failure()) && (steps.terraform_apply.outputs.stderr || steps.terraform_apply.outputs.stdout || steps.terraform_plan.outputs.stderr || steps.terraform_plan.outputs.stdout || steps.terraform_force_unlock.outputs.stderr || steps.terraform_force_unlock.outputs.stdout || steps.terraform_workspace.outputs.stderr || steps.terraform_workspace.outputs.stdout || steps.terraform_init.outputs.stderr || steps.terraform_init.outputs.stdout) }}
        uses: actions/github-script@d7906e4ad0b1822421a7e6a35d5ca353c962f410 # v6.4.1
        env:
          terraform_output: ${{ steps.terraform_apply.outputs.stderr || steps.terraform_apply.outputs.stdout || steps.terraform_plan.outputs.stderr || steps.terraform_plan.outputs.stdout || steps.terraform_force_unlock.outputs.stderr || steps.terraform_force_unlock.outputs.stdout || steps.terraform_workspace.outputs.stderr || steps.terraform_workspace.outputs.stdout || steps.terraform_init.outputs.stderr || steps.terraform_init.outputs.stdout }}
        with:
          script: |
            // From the terraform output, remove any lines which are related to reading or refreshing state, and then
            // store only the first 64800 characters of the output due to GitHub comment's character limit of 65536.
            const terraform_output = process.env.terraform_output
              .split("\n")
              .filter(
                (line) =>
                  !(
                    line.includes(": Reading...") ||
                    line.includes(": Read complete after") ||
                    line.includes(": Refreshing state...")
                  )
              )
              .join("\n")
              .substring(0, 64800);

            // Display the terraform output change summary as the collapsible content's title.
            const comment_summary = terraform_output
              .split("\n")
              .reverse()
              .find((line) => /^(Plan|Apply|Error|No changes)/.test(line)) ||
            "Terraform output.";

            // Display the terraform command authorship before the terraform output as the collapsible content's body.
            // Include the TFPLAN name in the hidden footer as a unique identifier for comment updates.
            const comment_body = `
            \`${process.env.INPUT_PROMPT}\`
            <details><summary>${comment_summary}</br>

            ###### ${{ github.workflow }} by @${{ github.actor }} via [${{ github.event_name }}](${{ github.event.repository.html_url }}/actions/runs/${{ github.run_id }}) at ${{ github.event.pull_request.updated_at || github.event.comment.updated_at }}.</summary>

            \`\`\`hcl
            ${terraform_output}
            \`\`\`
            </details>
            <!-- ${process.env.INPUT_TFPLAN} -->`;

            // Check if the bot has commented on the PR using the TFPLAN identifier.
            const { data: comments } = await github.rest.issues.listComments({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              per_page: 100,
              repo: context.repo.repo,
            });
            const botComment = comments.find((comment) => {
              return (
                comment.user.type === "Bot" &&
                comment.body.includes(`<!-- ${process.env.INPUT_TFPLAN} -->`)
              );
            });

            // Update the bot's comment if it exists, otherwise create a new comment.
            if (botComment) {
              github.rest.issues.updateComment({
                body: comment_body,
                comment_id: botComment.id,
                owner: context.repo.owner,
                repo: context.repo.repo,
              });
            } else {
              github.rest.issues.createComment({
                body: comment_body,
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
              });
            }

      - name: Update commit status
        if: ${{ (success() || failure()) && github.event.issue.pull_request }}
        uses: myrotvorets/set-commit-status-action@243b4f7e597f62335408d58001edf8a02cf3e1fd # v1.1.7
        with:
          sha: ${{ needs.pre.outputs.comment }}
          status: ${{ job.status }}
