---
name: TF Sample
on:
  pull_request:
    types: [opened, reopened, synchronize, closed]
    paths: [.github/workflows/tf_sample.yaml, stacks/**]

permissions:
  actions: read # Required for workflow query and artifact download.
  checks: write # Required for adding summary to check status.
  contents: read # Required for repository checkout.
  id-token: write # Required for assuming AWS role via OIDC provider.
  pull-requests: write # Required for commenting on PR.

env:
  AWS_REGION: us-east-1
  TF_VERSION: ~> 1.7.0
  TF_VAR_PREFIX: sample

jobs:
  Instance:
    runs-on: ubuntu-latest
    if: github.event.action != 'closed' || github.event.pull_request.merged

    strategy:
      fail-fast: false
      matrix:
        context: [dev, stg]

    environment: ${{ format('sample_instance/{0}', github.event.pull_request.merged && matrix.context || '') }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      - name: Authenticate AWS
        uses: aws-actions/configure-aws-credentials@e3dd6a429d7300a6a4c196c26e071d42e0343502 # v4.0.2
        with:
          aws-region: ${{ env.AWS_REGION }}
          role-to-assume: ${{ secrets.AWS_ROLE }}

      - name: Setup TF
        uses: hashicorp/setup-terraform@651471c36a6092792c552e8b1bef71e592b462d8 # v3.1.1
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: Provision TF
        uses: ./
        with:
          arg_command: ${{ github.event.action != 'closed' && 'plan' || 'apply' }}
          arg_chdir: stacks/sample_instance
          arg_var_file: ${{ format('env/{0}.tfvars', matrix.context) }}

  Bucket:
    runs-on: ubuntu-latest
    if: github.event.action != 'closed' || github.event.pull_request.merged

    strategy:
      fail-fast: false
      matrix:
        context: [dev, stg]

    environment: ${{ format('sample_bucket/{0}', github.event.pull_request.merged && matrix.context || '') }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      - name: Authenticate AWS
        uses: aws-actions/configure-aws-credentials@e3dd6a429d7300a6a4c196c26e071d42e0343502 # v4.0.2
        with:
          aws-region: ${{ env.AWS_REGION }}
          role-to-assume: ${{ secrets.AWS_ROLE }}

      - name: Setup TF
        uses: hashicorp/setup-terraform@651471c36a6092792c552e8b1bef71e592b462d8 # v3.1.1
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: Provision TF
        uses: ./
        with:
          arg_command: ${{ github.event.action != 'closed' && 'plan' || 'apply' }}
          arg_chdir: stacks/sample_bucket
          arg_backend_config: ${{ format('backend/{0}.tfbackend', matrix.context) }}
