---
name: TF Tests
on:
  pull_request:
    types: [opened, reopened, synchronize, closed]
    paths: [.github/workflows/tf_tests.yaml, scripts/**, tests/**]

jobs:
  tests:
    runs-on: ubuntu-latest
    if: github.event.action != 'closed' || github.event.pull_request.merged

    permissions:
      actions: read # Required for downloading artifact.
      checks: write # Required for adding status summary.
      contents: read # Required for checking out repository.
      pull-requests: write # Required for commenting on PR.

    strategy:
      fail-fast: false
      matrix:
        cli_tool: [tofu, terraform]
        test:
          - 10_fail_invalid_resource_type
          - 11_fail_data_source_error
          - 50_pass_one
          - 51_pass_character_limit
          - 52_pass_format_diff

    steps:
      - name: Checkout repository
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      - name: Provision TF
        id: tf
        continue-on-error: true
        uses: ./
        with:
          tf_cli_tool: ${{ matrix.cli_tool }}
          tf_cli_version: ~> 1.7.0
          arg_command: ${{ github.event.action != 'closed' && 'plan' || 'apply' }}
          arg_chdir: tests/${{ matrix.test }}

      # - name: Echo TF
      #   run: |
      #     echo "command: ${{ steps.tf.outputs.command }}"
      #     echo "comment_id: ${{ steps.tf.outputs.comment_id }}"
      #     echo "comment_summary: ${{ steps.tf.outputs.comment_summary }}"
      #     echo "plan_id: ${{ steps.tf.outputs.plan_id }}"
      #     echo "tf_fmt: ${{ steps.tf.outputs.tf_fmt }}"
      #     echo "tf_output: ${{ steps.tf.outputs.tf_output }}"

      - name: Echo github-script context
        if: always()
        uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea # v7.0.1
        with:
          script: console.log(JSON.stringify(context, null, 2))

      - name: Echo github context
        if: always()
        env:
          MATRIX_CONTEXT: ${{ toJSON(matrix) }}
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: |
          echo "$MATRIX_CONTEXT"
          echo "$GITHUB_CONTEXT"
